// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassLibrary1.N00_Config.Meta.Impl
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.CodeDom.Compiler;
    using System.IO;
    using System.CodeDom;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ComputationUnit : ComputationUnitBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 16 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"

    Func<Type, string> type2str = type =>
    {
        using (var writer = new StringWriter())
        {
            using (var provider = CodeDomProvider.CreateProvider("CSharp"))
            {
                provider.GenerateCodeFromExpression(new CodeTypeReferenceExpression(type), writer, null);
                return writer.ToString();
            }
        }
    };

    foreach(var us in Usings)
        WriteLine("using "+us+";");

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 32 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(" {\r\n    public class ");
            
            #line 33 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" {\r\n        public static ");
            
            #line 34 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type2str(ReturnType)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 34 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ComputeMethodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 34 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Parameters.Select(p => type2str(p.Value)+" "+p.Key))));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 36 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Code));
            
            #line default
            #line hidden
            this.Write("\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\rudolphm\Desktop\metrics-scribbling\ClassLibrary1\N00_Config\Meta\Impl\ComputationUnit.tt"

private string[] _UsingsField;

/// <summary>
/// Access the Usings parameter of the template.
/// </summary>
private string[] Usings
{
    get
    {
        return this._UsingsField;
    }
}

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private string _ClassNameField;

/// <summary>
/// Access the ClassName parameter of the template.
/// </summary>
private string ClassName
{
    get
    {
        return this._ClassNameField;
    }
}

private string _ComputeMethodNameField;

/// <summary>
/// Access the ComputeMethodName parameter of the template.
/// </summary>
private string ComputeMethodName
{
    get
    {
        return this._ComputeMethodNameField;
    }
}

private global::System.Type _ReturnTypeField;

/// <summary>
/// Access the ReturnType parameter of the template.
/// </summary>
private global::System.Type ReturnType
{
    get
    {
        return this._ReturnTypeField;
    }
}

private string _CodeField;

/// <summary>
/// Access the Code parameter of the template.
/// </summary>
private string Code
{
    get
    {
        return this._CodeField;
    }
}

private global::System.Collections.Generic.Dictionary<System.String,System.Type> _ParametersField;

/// <summary>
/// Access the Parameters parameter of the template.
/// </summary>
private global::System.Collections.Generic.Dictionary<System.String,System.Type> Parameters
{
    get
    {
        return this._ParametersField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool UsingsValueAcquired = false;
if (this.Session.ContainsKey("Usings"))
{
    this._UsingsField = ((string[])(this.Session["Usings"]));
    UsingsValueAcquired = true;
}
if ((UsingsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Usings");
    if ((data != null))
    {
        this._UsingsField = ((string[])(data));
    }
}
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    this._NamespaceField = ((string)(this.Session["Namespace"]));
    NamespaceValueAcquired = true;
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        this._NamespaceField = ((string)(data));
    }
}
bool ClassNameValueAcquired = false;
if (this.Session.ContainsKey("ClassName"))
{
    this._ClassNameField = ((string)(this.Session["ClassName"]));
    ClassNameValueAcquired = true;
}
if ((ClassNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ClassName");
    if ((data != null))
    {
        this._ClassNameField = ((string)(data));
    }
}
bool ComputeMethodNameValueAcquired = false;
if (this.Session.ContainsKey("ComputeMethodName"))
{
    this._ComputeMethodNameField = ((string)(this.Session["ComputeMethodName"]));
    ComputeMethodNameValueAcquired = true;
}
if ((ComputeMethodNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ComputeMethodName");
    if ((data != null))
    {
        this._ComputeMethodNameField = ((string)(data));
    }
}
bool ReturnTypeValueAcquired = false;
if (this.Session.ContainsKey("ReturnType"))
{
    this._ReturnTypeField = ((global::System.Type)(this.Session["ReturnType"]));
    ReturnTypeValueAcquired = true;
}
if ((ReturnTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ReturnType");
    if ((data != null))
    {
        this._ReturnTypeField = ((global::System.Type)(data));
    }
}
bool CodeValueAcquired = false;
if (this.Session.ContainsKey("Code"))
{
    this._CodeField = ((string)(this.Session["Code"]));
    CodeValueAcquired = true;
}
if ((CodeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Code");
    if ((data != null))
    {
        this._CodeField = ((string)(data));
    }
}
bool ParametersValueAcquired = false;
if (this.Session.ContainsKey("Parameters"))
{
    this._ParametersField = ((global::System.Collections.Generic.Dictionary<System.String,System.Type>)(this.Session["Parameters"]));
    ParametersValueAcquired = true;
}
if ((ParametersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Parameters");
    if ((data != null))
    {
        this._ParametersField = ((global::System.Collections.Generic.Dictionary<System.String,System.Type>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class ComputationUnitBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
